### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by EmmaZhu**
Microsoft Azure Storage Data Movement Library v0.3.0

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@EmmaZhu__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (emmazhu). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by nowenL** [comment]
Why the document changes show up again in this PR, they are in the dev branch already.

**Comment by EmmaZhu** [comment]
@nowenL Talked with Vincent, the release should be on Master branch, this PR is sent to master branch, that the commits in dev branch are also included in this PR.

**Comment by nowenL** [comment]
I see. Verified with WinMerge, this PR and coreclr branch are identical. I thinks it's good to merge.

**Pull request merged**
