### PR TITLE
Reduce CPU usage from TransferScheduler

### PR DESCRIPTION
**Pull request by neilrees**
To address issue: https://github.com/Azure/azure-storage-net-data-movement/issues/66

The task started by `TransferScheduler` spins waiting for work and consumes a lot of CPU even when there is nothing to do.  

* Introduce an event to block the task until more work is provided

Ideally the task would exit and a new task would be created when new work arrives but wanted to keep this change thin.

Other fixes considered:
1.  Adding a shutdown method to TransferManager : https://github.com/neilrees/azure-storage-net-data-movement/commit/2c718995b342f28a4ae344d842d7ddb56efa226c
But there's a potential race condition of one thread shutting down the transfer manager whilst someone else is adding more work.

2.  Also considered performing each interaction with DMLib in it's own app domain and shut down the domain when the upload is complete.  But the we loose the holistic view that `TransferManager` has of all the copies that we have going on.

### CODE REVIEW

**Comment by vinjiang** [comment]
Can one of the admins verify this patch?

**Comment by EmmaZhu** [comment]
ok to test

**Comment by EmmaZhu** [comment]
@neilrees  
Thanks for the promising contribution.
For the change is in the critical scheduler thread, we'd need a round of Perf test to get it in which would take some time. Will let you know when we got the result.

**Comment by neilrees** [comment]
@EmmaZhu Have disposed the queueAddedEvent whwn the TransferScheduler disposed.

The irony of this is that if a consuming client could actually dispose the TransferScheduler we wouldn't have this issue ;)

**Comment by EmmaZhu** [comment]
ok to test

**Comment by EmmaZhu** [comment]
@neilrees 
I've done a test against DMLib with version of 0.8.0 and 0.8.1, (without this change from you). 
The testing code is like following:
```
CloudBlobContainer container = new CloudBlobContainer(new Uri("http://myaccount.blob.core.windows.net/container1/"),
                new StorageCredentials("myaccount", "***"));
           string sourceDir = @"sourcedir";

            DirectoryTransferContext transferContext = new DirectoryTransferContext();
            transferContext.FileTransferred += (sender, eventArgs) =>
            {
                Console.WriteLine("Succeeded to upload {0}", eventArgs.Source);
                TransferManager.Configurations.UserAgentPrefix = "DMLibTest";
            };

            transferContext.FileFailed += (sender, eventArgs) =>
            {
                Console.WriteLine("Failed to upload {0} with Exception: {1}", eventArgs.Source, eventArgs.Exception);
            };

            transferContext.ShouldOverwriteCallbackAsync = DirectoryTransferContext.ForceOverwrite;

            try
            {
                TransferManager.UploadDirectoryAsync(sourceDir, container.GetDirectoryReference("TrailingSpaceTest"), new UploadDirectoryOptions()
                {
                    Recursive = true
                }, transferContext).Wait();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }


            Console.WriteLine("Press any key to exist");
            var key = Console.ReadKey();
```

First it enables TransferManager to do some files' uploading which will start TransferScheduler to run at background. Then it wait for a key, and do nothing to see how the CPU usage is. Seems it doesn't have much CPU usage, after some time, the CPU usage is between 0 ~ 1% which seems acceptable to me. I run this test on a 8 cores machine. 

Would you also like to run a test with it?

**Comment by roycornelissen** [comment]
Any updates on this? We're seeing the same issue with constant high CPU usage as soon as the TransferManager has been in action once to do a download.

**Comment by EmmaZhu** [comment]
Hi @roycornelissen,

I'm trying to have a repro for this issue, but with several different tries, seems the CPU usage can always decrease to 0~1% which seems not a high usage.

If the CPU usage can decrease to a lower value, we'd prefer not to use one more lock. If the CPU usage keeps in a high value, we should take a fix on it. For now, we'd need to repro it and validate the fix. 

I have tried with data set of 1*1KB, 10 * 2GB, and 100 * 2GB on OS of Windows 2016 Server, and Windows 8, but still cannot see the high CPU usage after transfer is completed. 

Could you help to share your repro info, like: data set, OS version, Framework version (.Net Framework 4.5, or .Net Core or any other framework).

Thanks
Emma

**Comment by roycornelissen** [comment]
Hi @EmmaZhu,

Thanks for your reply. Some more details on our scenario:

- WPF Desktop app
- .NET Framework v 4.6.1
- OS: Windows 10, 1809 Build 17763.379 (most user systems run a fairly recent build of Windows 10)
- Microsoft.Azure.Storage.DataMovement 0.10.1

In order to remove any possible noise and complexity of our app's business logic, I've stripped down our scenario to a bare File > New Project WPF application.

We first noticed that our app had high CPU usage shortly after launching, and I managed to pin that down to a single line of code which was hit soon after the app launches:

`TransferManager.Configurations.ParallelOperations = Environment.ProcessorCount * 8;`

By removing this line, CPU usage went flat, until the first file download was triggered in the app. By looking at the source code of this library, I figured that using the static `TransferManager.Configurations.ParallelOperations` setter, some initialization code was triggered, which sets the scheduler loop in motion. So removing the line only turned out to postpone the problem.

If you run the WPF app in the attached project, put in a URL for a large blob (I tested with a 500Mb blob and a 1.5Mb one), you should be able to reproduce the issue. After the download is finished, CPU usage remains high and doesn't seem to cease even after running for minutes.

I don't know the internals of this library well enough to judge whether this PR is the right fix for the problem, but isn't it possible to implement the queue in a more push-like fashion, like with `System.Reactive`?

[CPUUsageRepro.zip](https://github.com/Azure/azure-storage-net-data-movement/files/2988463/CPUUsageRepro.zip)

**Comment by EmmaZhu** [comment]
@roycornelissen 

Thanks a lot for the repro.

I've just tried with your repro with downloading a 8GB blob, on .Net Framework 4.6.1, and Windows 10.0.17763 N/A Build 17763. When it starts the downloading, CPU usage could be up to 40%, CPU usage will decrease to 0~1% after the downloading is completed. Below is perfmon screanshot for the CPU usage.

image

In the DataMovement library, the scheduler thread will always keep running. It uses SpinOnce which keeps a counter internally and switch the thread out (with Yield) when the count reaches a threshold. With this behavior, the scheduler thread should not have too high CPU usage when there's nothing to do.  The high CPU usage during transferring is by design currently, DataMovement Library doesn't have the functionality to limit transfer speed for now. But if the CPU usage keeps in a high level even when there's nothing to do, we should definitely fix it. 

For now, I still cannot repro the issue. From your description, seems it's easy to repro in your environment. I'll look around to try to find out what else could take effect on the different behaviors. May still need your help in further investigation later. 

Thanks
Emma

**Comment by EmmaZhu** [comment]
I'll take this PR into the pr112 branch, and run some test against it. Will update you about the result.

**Comment by EmmaZhu** [comment]
I just found a new way to reduce CPU when there's no work:
We can wait on controllerQueue, which is a blocking collection, when there's no transfer going on. This way, it won't need to introduce a new event variable.


Thanks
Emma

**Pull request merged**
