### PR TITLE
Small file optimization S3 - Use PutBlob to upload block blob when blob size <= 4MB

### PR DESCRIPTION
**Pull request by jiacfan**
Small file optimization S3 - Use PutBlob to upload block blob when blob size <= 4MB

### CODE REVIEW

**Comment by vinjiang** [comment]
Can one of the admins verify this patch?

**Comment by EmmaZhu** [comment]
test it please

**Comment by EmmaZhu** [comment]
test this please

**Comment by EmmaZhu** [comment]
add to whitelist

**Pull request merged**
